import Link from "next/link";
import { BarChart3 } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen">
      <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container mx-auto flex h-14 items-center px-4">
          <Link href="/" className="flex items-center gap-2 font-semibold">
            <BarChart3 className="h-5 w-5 text-primary" />
            Skill Gap Analyzer
          </Link>
        </div>
      </header>

      <main className="container mx-auto max-w-2xl px-4 py-12">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Last updated: March 2026
        </p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Service description
            </h2>
            <p>
              Skill Gap Analyzer is a web application that compares your
              resume against a job description to identify skill gaps, provide
              a match score, and generate personalized learning roadmaps. The
              analysis is powered by large language models and is provided as
              a best-effort tool — it should not be your sole basis for career
              decisions.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Accounts and credits
            </h2>
            <p>
              Every account receives 1 free analysis credit upon
              registration. Additional credits can be purchased in packs
              ($5 for 10, $12 for 30, $25 for 100). Credits do not expire.
              Each analysis consumes 1 credit. Cached results (identical
              resume + job description within 24 hours) do not consume a
              credit.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Payments
            </h2>
            <p>
              All payments are processed by DodoPayments, which acts as the
              Merchant of Record. DodoPayments handles billing, tax
              collection, refunds, and chargebacks. By purchasing credits,
              you agree to DodoPayments&apos; terms of service. Refund
              requests should be directed to our support email and are
              handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Acceptable use
            </h2>
            <p>
              You agree to use the service for personal career development
              purposes. You may not: (a) reverse-engineer, scrape, or
              automate requests to the service; (b) submit content that is
              unlawful, fraudulent, or violates the rights of others;
              (c) attempt to circumvent rate limits, credit checks, or
              authentication; (d) resell or redistribute analysis results
              commercially without permission.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Account termination
            </h2>
            <p>
              We may suspend or terminate your account if you violate these
              terms. You may delete your account at any time through
              settings, which permanently removes all your data. Unused
              credits are non-refundable upon voluntary account deletion.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Disclaimers
            </h2>
            <p>
              The service is provided &ldquo;as is&rdquo; without warranty of
              any kind. Analysis results are generated by AI and may contain
              inaccuracies. We do not guarantee that following the suggested
              roadmap or resume changes will result in a job offer. Scores
              are relative and should be used as one data point among many in
              your job search.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Limitation of liability
            </h2>
            <p>
              To the maximum extent permitted by law, Skill Gap Analyzer and
              its operators shall not be liable for any indirect, incidental,
              or consequential damages arising from your use of the service,
              including but not limited to lost opportunities, lost data, or
              career decisions made based on analysis results. Our total
              liability is limited to the amount you paid for credits in the
              12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Changes to these terms
            </h2>
            <p>
              We may update these terms from time to time. If we make
              material changes, we&apos;ll notify you via email or a notice
              on the site. Continued use after changes constitutes
              acceptance.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-foreground">
              Contact
            </h2>
            <p>
              For questions about these terms, email{" "}
              <a
                href="mailto:support@skillgap.dev"
                className="text-primary underline-offset-4 hover:underline"
              >
                support@skillgap.dev
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t py-8">
        <div className="container mx-auto flex items-center justify-between px-4 text-sm text-muted-foreground">
          <div className="flex items-center gap-2">
            <BarChart3 className="h-4 w-4" />
            Skill Gap Analyzer
          </div>
          <div className="flex gap-4">
            <Link href="/pricing" className="hover:underline">
              Pricing
            </Link>
            <Link href="/privacy" className="hover:underline">
              Privacy
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
